### ISSUE TITLE
RootTools.isRootAvailable() exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Kang29/roottools#49]
```
What steps will reproduce the problem?
The problem is very hard to reproduce. It happens randomly on several different 
devices.

What is the expected output? What do you see instead?
I'm simply looking t get the results from isRootAvailable but instead my app 
freeze and crash when I get this exception.

What version of the product are you using? On what operating system?
I'm using RootTools version 2.5.0. I saw this issue happen on all sort of OS, 
2.3, 4.0, 4.2. All OS I had this issue were NOT rooted.

Please provide any additional information below.
I know this is coming from RootTools.isRootAvailable() because it is the only 
command I'm using from RootTools

Here is the exception I get
01-01 01:22:51.964: I/System(9632): libcore.io.ErrnoException: kill failed: 
ESRCH (No such process)
01-01 01:22:51.964: I/System(9632):     at libcore.io.Posix.kill(Native Method)
01-01 01:22:51.964: I/System(9632):     at 
libcore.io.ForwardingOs.kill(ForwardingOs.java:77)
01-01 01:22:51.964: I/System(9632):     at 
java.lang.ProcessManager$ProcessImpl.destroy(ProcessManager.java:257)
01-01 01:22:51.964: I/System(9632):     at 
com.stericson.RootTools.execution.Shell$3.run(Shell.java:433)
01-01 01:22:51.964: I/System(9632):     at java.lang.Thread.run(Thread.java:856)

When this crash happens all sort of stuff start to go wrong in the phone and I 
need to reboot it in order to get the phone working properly again.
```

Original issue reported on code.google.com by `kevin.la...@gmail.com` on 19 Sep 2013 at 5:08

**Comment by GoogleCodeExporter** [comment]
```
This issue should be resolved with version 3.0+
```

Original comment by `Stericso...@gmail.com` on 7 Oct 2013 at 1:53
- Changed state: **Done**
